const data = {
  formPropertyVO: [
    {
      id: 'commercialId',
      name: '商户编号',
      readable: true,
      required: true,
      type: 'list',
      writable: true,
      items: [
        {
          id: 'serviceName',
          name: '服务名称',
          readable: true,
          required: true,
          type: 'string',
          writable: false,
        },
        {
          id: 'serviceNumber',
          name: '服务次数',
          readable: true,
          required: true,
          type: 'string',
          writable: false,
        },
      ],
    },
    {
      id: 'commercialName',
      name: '商户名称',
      readable: true,
      required: true,
      type: 'string',
      writable: false,
    },
    {
      id: 'brandName',
      name: '品牌名称',
      readable: true,
      required: true,
      type: 'string',
      writable: false,
    },
    {
      id: 'businessConsultant',
      name: '业务顾问',
      readable: true,
      required: true,
      type: 'string',
      writable: true,
    },
    {
      id: 'businessConsultantPhone',
      name: '业务顾问电话',
      readable: true,
      required: true,
      type: 'string',
      writable: true,
    },
    {
      id: 'businessContacts',
      name: '商户联系人',
      readable: true,
      required: false,
      type: 'string',
      writable: false,
    },
    {
      id: 'commercialAddress',
      name: '详细地址',
      readable: true,
      required: false,
      type: 'string',
      writable: false,
    },
    {
      id: 'contractWay',
      name: '联系方式',
      readable: true,
      required: true,
      type: 'string',
      writable: false,
    },
    {
      id: 'serviceConsultant',
      name: '服务顾问',
      readable: true,
      required: true,
      type: 'string',
      writable: true,
    },
    {
      id: 'serviceConsultantPhone',
      name: '服务顾问电话',
      readable: true,
      required: true,
      type: 'string',
      writable: true,
    },
    {
      id: 'serviceType',
      name: '服务类型',
      readable: true,
      required: true,
      type: 'enum',
      writable: true,
    },
    {
      id: 'serviceStartDate',
      name: '合约日期',
      readable: true,
      required: true,
      type: 'date',
      writable: true,
    },
    {
      id: 'serviceEndDate',
      name: '合约日期',
      readable: true,
      required: true,
      type: 'date',
      writable: true,
    },
    {
      id: 'serviceTimes',
      name: '服务次数',
      readable: true,
      required: true,
      type: 'string',
      writable: true,
    },
    {
      id: 'serviceConfirmFiles',
      name: '服务确认单',
      readable: true,
      required: true,
      type: 'string',
      writable: true,
    },
    {
      id: 'letterOfCommitment',
      name: '承诺书',
      readable: true,
      required: true,
      type: 'string',
      writable: true,
    },
  ],
};

export const wrapperData = {
  code: 0,
  data: data,
  msg: '成功[OK]',
  msgContent: '[RESPONSE IS OK]',
  msgId: '047d1f272a2540bca5d1ffc2da3d99a4',
  utc: '20180523150547',
};
